### ISSUE TITLE
Text leads to error message

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-workflow-editor#19] opened 2016-03-18 08:30 UTC
When I submit this text to e-Entity, dataset viaf, language english, mode spot,link,classify, then I get an error message.

Text:

```
Dublin Castle is the heart of historic Dublin. In fact the city gets its name from the Black Pool - 'Dubh Linn' which was on the site of the present Castle garden.

The Castle stands on the ridge on a strategic site at the junction of the River Liffey and its tributary the Poddle, where the original fortification may have been an early Gaelic Ring Fort.

Later a Viking Fortress stood on this site - a portion of which is on view to visitors in the ' Mediaeval Undercroft' which also includes the remains of the original 13th century Castle.

The south range houses the magnificent State Apartments that were built as the residential quarters of the Viceregal court. They are now the venue for Presidential Inaugurations, State Functions and Ireland's Presidencies of the European Union.

The State Apartments, Medieval Undercroft and Chapel Royal are open to visitors. On occasions, the State Apartments may be closed for State Purposes.

The Dubhlinn Tearooms situated in the State Apartments are open Monday to Sunday."
```

Error:

<img width="976" alt="screen shot 2016-03-16 at 12 50 43" src="https://cloud.githubusercontent.com/assets/10537540/13872601/0d42a1ee-ecec-11e5-872e-7e5c76f15d87.png">

**Comment by josauder** [comment] 2016-03-18 10:04
This was caused by the rdfQuery library which does not accept newlines in Strings for some reason.

I have worked around this by removing all newlines in the response - I don't think it is worth the effort to go into the code of the rdfQuery library for this one.

**Comment by josauder** [comment] 2016-03-18 10:05
What do you think? Can we close this issue?

**Comment by jnehring** [comment] 2016-03-18 10:27
Did you upload this modification to freme-dev? I cannot see any difference.

What does stripping of newlines exactly mean? When I submit a document

```
Line 1
Line 2
```

Does it get visualised in the e-Service output window as 

```
Line1Line2
```

?

**Comment by josauder** [comment] 2016-03-18 10:45
I did upload it - you might have to clear your browser cache.

Newlines are replaced with a single space so that

```
Dublin Castle is the heart of historic Dublin. In fact the city gets its name from the Black Pool - 'Dubh Linn' which was on the site of the present Castle garden.

The Castle stands on the ridge on a strategic site at the junction of the River Liffey and its tributary the Poddle, where the original fortification may have been an early Gaelic Ring Fort.

Later a Viking Fortress stood on this site - a portion of which is on view to visitors in the ' Mediaeval Undercroft' which also includes the remains of the original 13th century Castle.

The south range houses the magnificent State Apartments that were built as the residential quarters of the Viceregal court. They are now the venue for Presidential Inaugurations, State Functions and Ireland's Presidencies of the European Union.

The State Apartments, Medieval Undercroft and Chapel Royal are open to visitors. On occasions, the State Apartments may be closed for State Purposes.

The Dubhlinn Tearooms situated in the State Apartments are open Monday to Sunday."
```

gets visualized as:

```
 Dublin Castle is the heart of historic Dublin. In fact the city gets its name from the Black Pool - 'Dubh Linn' which was on the site of the present Castle garden. The Castle stands on the ridge on a strategic site at the junction of the River Liffey and its tributary the Poddle, where the original fortification may have been an early Gaelic Ring Fort. Later a Viking Fortress stood on this site - a portion of which is on view to visitors in the ' Mediaeval Undercroft' which also includes the remains of the original 13th century Castle. The south range houses the magnificent State Apartments that were built as the residential quarters of the Viceregal court. They are now the venue for Presidential Inaugurations, State Functions and Ireland's Presidencies of the European Union. The State Apartments, Medieval Undercroft and Chapel Royal are open to visitors. On occasions, the State Apartments may be closed for State Purposes. The Dubhlinn Tearooms situated in the State Apartments are open Monday to Sunday."
```

**Comment by jnehring** [comment] 2016-03-18 10:51
Right I had to refresh the browser cache.

Stripping newlines is not good. People want to use the workflow editor to find out the behaviour of freme without dealing with NIF and so on. So the UI should not modify the content.

Can you find another solution to stripping newlines?

**Closed as completed** 2016-03-18 14:14 UTC
Labels: bug
